gateways:
  local:
    connection:
      type: spark
      config_dir: ./
    state_connection:
      type: duckdb
      database: ./lakehouse/sqlmesh_state.duckdb

default_gateway: local
default_target_environment: dev

model_defaults:
  dialect: duckdb
  start: 2025-01-01

model_naming:
  infer_names: True