gateways:
  local:
    connection:
      type: duckdb
      database: "./lakehouse/lakehouse.duckdb"
      extensions:
        - delta
  
  remote:
    connection:
      type: motherduck
      database: adventure_works

default_gateway: remote

model_defaults:
  dialect: duckdb
  start: 2025-01-01

model_naming:
  infer_names: True